name: 'TruffleHog OSS'
description: 'Scan Github Actions with TruffleHog'
author: Truffle Security Co. <support@trufflesec.com>

inputs:
  path:
    description: Repository path
    required: true
  base:
    description: Start scanning from here (usually main branch).
    required: true
  head:
    description: Scan commits until here (usually dev branch).
    required: false
  falsePositives:
    description: Path to file with newline separated strings to ignore as false positives.
    required: false
  debug:
    description: Show debug information.
    required: false
  trace:
    description: Show trace information.
    required: false
branding:
  icon: "shield"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - git
    - file://${{ inputs.path }}
    - --since-commit
    - ${{ inputs.base }}
    - ${{ inputs.head && '--branch' }}
    - ${{ inputs.head }}
    - ${{ inputs.falsePositives && '--false-positives' }}
    - ${{ inputs.falsePositives }}
    - ${{ inputs.debug && '--debug' }}
    - ${{ inputs.trace && '--trace' }}
    - --fail
